import { WINE_TYPE_LABELS, type WineTypeId } from '@/features/survey/constants/wine-survey';

export type GrapeProfile = {
  id: string;
  nameKo: string;
  nameEn: string;
  category: WineTypeId;
  sweetness: number;
  tannin: number;
  body: number;
  /** 1=낮음 ~ 5=높음 (신 맛·머금었을 때 입안에 침이 고이는 정도) */
  acidity: number;
  aromaStyle: number;
  foods: string[];
  styleHint: string;
};

export const findGrapeProfileByNameKo = (nameKo: string): GrapeProfile | undefined =>
  GRAPE_CATALOG.find((g) => g.nameKo === nameKo);

export const getWineKindLabelByGrapeNameKo = (nameKo: string): string | undefined => {
  const g = findGrapeProfileByNameKo(nameKo);
  if (!g) {
    return undefined;
  }
  return WINE_TYPE_LABELS[g.category];
};

const GRAPE_RANK_SHORT_LABELS = ['1차', '2차', '3차'] as const;

export const formatRankedGrapesSummary = (nameKos: string[]): string => {
  return nameKos
    .map((name, i) => {
      const rank = GRAPE_RANK_SHORT_LABELS[i] ?? `${i + 1}차`;
      const kind = getWineKindLabelByGrapeNameKo(name);
      return kind ? `${rank} ${name} · ${kind}` : `${rank} ${name}`;
    })
    .join(' · ');
};

export const GRAPE_CATALOG: GrapeProfile[] = [
  {
    id: 'cabernet',
    nameKo: '카베르네 소비뇽',
    nameEn: 'Cabernet Sauvignon',
    category: 'red',
    sweetness: 1,
    tannin: 5,
    body: 5,
    acidity: 3,
    aromaStyle: 4.5,
    foods: ['스테이크', '양갈비', '바비큐', '불고기', '갈비찜'],
    styleHint: '구조감 있는 보르도 스타일',
  },
  {
    id: 'merlot',
    nameKo: '메를로',
    nameEn: 'Merlot',
    category: 'red',
    sweetness: 2,
    tannin: 3,
    body: 4,
    acidity: 2.5,
    aromaStyle: 3,
    foods: ['치킨', '제육볶음', '햄버거', '파스타'],
    styleHint: '부드러운 미디엄 바디 레드',
  },
  {
    id: 'pinot_noir',
    nameKo: '피노 누아',
    nameEn: 'Pinot Noir',
    category: 'red',
    sweetness: 1,
    tannin: 2,
    body: 2.5,
    acidity: 4,
    aromaStyle: 2,
    foods: ['육전', '닭갈비', '연어', '보쌈'],
    styleHint: '부르고뉴 스타일 · 산도 중심',
  },
  {
    id: 'tempranillo',
    nameKo: '템프라니요',
    nameEn: 'Tempranillo',
    category: 'red',
    sweetness: 1,
    tannin: 3.5,
    body: 4,
    acidity: 3,
    aromaStyle: 3.5,
    foods: ['바비큐', '소고기구이', 'LA갈비', '직화구이'],
    styleHint: '리오하 스타일',
  },
  {
    id: 'sangiovese',
    nameKo: '산지오베제',
    nameEn: 'Sangiovese',
    category: 'red',
    sweetness: 1,
    tannin: 3,
    body: 3,
    acidity: 4,
    aromaStyle: 2.5,
    foods: ['피자', '김치전', '닭볶음탕'],
    styleHint: '토스카나 스타일',
  },
  {
    id: 'nebbiolo',
    nameKo: '네비올로',
    nameEn: 'Nebbiolo',
    category: 'red',
    sweetness: 1,
    tannin: 5,
    body: 5,
    acidity: 4.5,
    aromaStyle: 4,
    foods: ['스테이크', '갈비찜', '한우구이', '장조림'],
    styleHint: '바롤로급 구조감',
  },
  {
    id: 'zinfandel',
    nameKo: '진판델',
    nameEn: 'Zinfandel',
    category: 'red',
    sweetness: 2.5,
    tannin: 4,
    body: 5,
    acidity: 3,
    aromaStyle: 3.5,
    foods: ['바비큐', '피자', '햄버거', '닭강정', '양념치킨'],
    styleHint: '과실감 풍부한 뉴월드 레드',
  },
  {
    id: 'sauvignon_blanc',
    nameKo: '소비뇽 블랑',
    nameEn: 'Sauvignon Blanc',
    category: 'white',
    sweetness: 1,
    tannin: 1,
    body: 1.5,
    acidity: 5,
    aromaStyle: 1.5,
    foods: ['굴', '회', '샐러드', '해산물'],
    styleHint: '산도 중심 · 허브 시트러스',
  },
  {
    id: 'chardonnay',
    nameKo: '샤르도네',
    nameEn: 'Chardonnay',
    category: 'white',
    sweetness: 2,
    tannin: 1,
    body: 4,
    acidity: 3,
    aromaStyle: 4,
    foods: ['치킨', '크림파스타', '전', '랍스터'],
    styleHint: '오크 터치 버터리 화이트',
  },
  {
    id: 'chenin_blanc',
    nameKo: '슈냉 블랑',
    nameEn: 'Chenin Blanc',
    category: 'white',
    sweetness: 3,
    tannin: 1,
    body: 3,
    acidity: 4,
    aromaStyle: 3,
    foods: ['치즈', '잡채', '닭요리'],
    styleHint: '꿀·꽃 향 미디엄 바디',
  },
  {
    id: 'riesling',
    nameKo: '리슬링',
    nameEn: 'Riesling',
    category: 'white',
    sweetness: 3,
    tannin: 1,
    body: 2,
    acidity: 4.5,
    aromaStyle: 2.5,
    foods: ['매운 음식', '김치찜', '제육볶음'],
    styleHint: '스파이시 푸드 페어링',
  },
  {
    id: 'pinot_gris',
    nameKo: '피노 그리',
    nameEn: 'Pinot Gris',
    category: 'white',
    sweetness: 2.5,
    tannin: 1,
    body: 3,
    acidity: 3,
    aromaStyle: 2.5,
    foods: ['치킨', '보쌈', '수육', '만두'],
    styleHint: '배·멜론 뉘트럴 화이트',
  },
  {
    id: 'gewurztraminer',
    nameKo: '게뷔르츠트라미너',
    nameEn: 'Gewürztraminer',
    category: 'white',
    sweetness: 4,
    tannin: 1,
    body: 3.5,
    acidity: 2.5,
    aromaStyle: 3.5,
    foods: ['커리', '양념치킨', '떡볶이', '마라요리'],
    styleHint: '향신료·리치 아로마',
  },
  {
    id: 'gruner',
    nameKo: '그뤼너 벨트리너',
    nameEn: 'Grüner Veltliner',
    category: 'white',
    sweetness: 1,
    tannin: 1,
    body: 2,
    acidity: 4.5,
    aromaStyle: 1.5,
    foods: ['채소요리', '나물', '두부요리', '산채비빔밥'],
    styleHint: '허브·흰후추 미네랄',
  },
  {
    id: 'bdb',
    nameKo: '샴페인 Blanc de Blancs',
    nameEn: 'Blanc de Blancs',
    category: 'sparkling',
    sweetness: 1,
    tannin: 1,
    body: 2.5,
    acidity: 4.5,
    aromaStyle: 2,
    foods: ['굴', '회', '캐비어', '해산물'],
    styleHint: 'Blanc de Blancs · 샤르도네 베이스',
  },
  {
    id: 'bdn',
    nameKo: '샴페인 Blanc de Noirs',
    nameEn: 'Blanc de Noirs',
    category: 'sparkling',
    sweetness: 1,
    tannin: 2,
    body: 3.5,
    acidity: 3.5,
    aromaStyle: 3.5,
    foods: ['치킨', '오리', '육전'],
    styleHint: 'Blanc de Noirs · 브리오슈',
  },
  {
    id: 'cremant',
    nameKo: '크레망',
    nameEn: 'Crémant',
    category: 'sparkling',
    sweetness: 1,
    tannin: 1,
    body: 2.5,
    acidity: 3.5,
    aromaStyle: 2.5,
    foods: ['치즈', '전', '샐러드'],
    styleHint: '부드러운 버블 프렌치 크레망',
  },
  {
    id: 'cava',
    nameKo: '카바',
    nameEn: 'Cava',
    category: 'sparkling',
    sweetness: 1,
    tannin: 1,
    body: 2,
    acidity: 4,
    aromaStyle: 2,
    foods: ['튀김', '해물파전', '감자전'],
    styleHint: '드라이 · 고소한 스파클링',
  },
  {
    id: 'prosecco',
    nameKo: '프로세코',
    nameEn: 'Prosecco',
    category: 'sparkling',
    sweetness: 1.5,
    tannin: 1,
    body: 1.5,
    acidity: 3,
    aromaStyle: 1.5,
    foods: ['과일', '샌드위치', '브런치'],
    styleHint: '청사과 · 가벼운 이탈리아 스파클링',
  },
  {
    id: 'moscato',
    nameKo: '모스카토 다스티',
    nameEn: "Moscato d'Asti",
    category: 'sparkling',
    sweetness: 5,
    tannin: 1,
    body: 2,
    acidity: 2.5,
    aromaStyle: 2,
    foods: ['케이크', '과일', '약과', '호떡'],
    styleHint: '달콤한 저알코올 스파클링',
  },
  {
    id: 'grenache_rose',
    nameKo: '그르나슈 로제',
    nameEn: 'Grenache Rosé',
    category: 'rose',
    sweetness: 1,
    tannin: 1,
    body: 2,
    acidity: 3,
    aromaStyle: 2,
    foods: ['샐러드', '닭요리', '골뱅이무침'],
    styleHint: '프로방스형 드라이 로제',
  },
  {
    id: 'cinsault_rose',
    nameKo: '생소 로제',
    nameEn: 'Cinsault Rosé',
    category: 'rose',
    sweetness: 1,
    tannin: 1,
    body: 1.5,
    acidity: 3.5,
    aromaStyle: 1.5,
    foods: ['김밥', '파스타', '피크닉 음식'],
    styleHint: '가벼운 베리 로제',
  },
  {
    id: 'pinot_rose',
    nameKo: '피노 누아 로제',
    nameEn: 'Pinot Noir Rosé',
    category: 'rose',
    sweetness: 1,
    tannin: 1,
    body: 2,
    acidity: 4,
    aromaStyle: 2,
    foods: ['연어', '육회', '육전'],
    styleHint: '섬세한 산도 로제',
  },
  {
    id: 'port',
    nameKo: '포트 와인',
    nameEn: 'Port wine',
    category: 'sweet',
    sweetness: 5,
    tannin: 3,
    body: 4.5,
    acidity: 2.5,
    aromaStyle: 4,
    foods: ['초콜릿', '약과', '블루치즈', '곶감'],
    styleHint: '진한 디저트 와인',
  },
  {
    id: 'ice_wine',
    nameKo: '아이스와인',
    nameEn: 'Ice wine',
    category: 'sweet',
    sweetness: 5,
    tannin: 1,
    body: 3,
    acidity: 4,
    aromaStyle: 3.5,
    foods: ['과일', '치즈', '한과'],
    styleHint: '꿀·살구 아이스와인',
  },
  {
    id: 'noble_rot',
    nameKo: '귀부와인',
    nameEn: 'Noble rot wine',
    category: 'sweet',
    sweetness: 5,
    tannin: 1,
    body: 4,
    acidity: 3.5,
    aromaStyle: 4.5,
    foods: ['블루치즈', '호두정과', '유과'],
    styleHint: '소테른 스타일 복합미',
  },
];
